name: Fetch Weather Data Hourly

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch:

jobs:
  fetch-weather:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install requests
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run weather fetch script
        run: python data/fetch-weather.py

      - name: List generated JSON files
        run: ls -lh data/*.json

